# Generated by Django 2.2.6 on 2020-03-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аватарка'),
        ),
    ]
