# Generated by Django 2.2.6 on 2020-04-03 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='departmenttype',
            options={'verbose_name': 'Тип подразделения', 'verbose_name_plural': 'Типы подразделений'},
        ),
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.DepartmentType', verbose_name='Тип подразделения'),
        ),
    ]
