# Generated by Django 2.2.6 on 2020-03-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200302_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='type',
            new_name='department_type',
        ),
    ]
