# Generated by Django 2.2.6 on 2020-05-11 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200511_0505'),
        ('companies', '0002_auto_20200507_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventemployee',
            old_name='event',
            new_name='event_instance',
        ),
        migrations.RemoveField(
            model_name='event',
            name='document_template',
        ),
        migrations.RemoveField(
            model_name='event',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='eventemployee',
            name='id',
        ),
        migrations.AddField(
            model_name='eventemployee',
            name='entity_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Entity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commissionemployee',
            name='member_status',
            field=models.PositiveIntegerField(choices=[(1, 'Председатель'), (2, 'Секретарь'), (3, 'Член')], default=3, verbose_name='Статус участника'),
        ),
        migrations.AlterField(
            model_name='eventdocumenttemplate',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.PROTECT, related_name='event_to_doc_template', to='companies.Event', verbose_name='Мероприятие'),
        ),
    ]
