# Generated by Django 2.2.6 on 2020-04-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_position_boss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
        migrations.AlterModelOptions(
            name='equipmentgroup',
            options={'verbose_name': 'Группа инструментов', 'verbose_name_plural': 'Группы инструментов'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'verbose_name': 'Рабочее место', 'verbose_name_plural': 'Рабочие места'},
        ),
        migrations.RemoveField(
            model_name='workplace',
            name='name',
        ),
    ]
