# Generated by Django 2.2.6 on 2020-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200512_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страховой номер (СНИЛС)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pers_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Табельный номер'),
        ),
    ]
