# Generated by Django 2.2.6 on 2020-04-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200403_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='sex',
            new_name='gender',
        ),
    ]
