# Generated by Django 2.2.6 on 2020-04-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20200403_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аватарка'),
        ),
    ]
