# Generated by Django 2.2.6 on 2020-04-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20200403_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='order_num',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
    ]
