# Generated by Django 2.2.6 on 2020-05-13 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20200513_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='companies.EventType', verbose_name='Вид мероприятия'),
        ),
    ]
