# Generated by Django 2.2.6 on 2020-05-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20200513_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='company_boss',
            field=models.BooleanField(default=False, verbose_name='Руководитель компании'),
        ),
    ]
