# Generated by Django 2.2.6 on 2020-04-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_department_order_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='member_status',
        ),
        migrations.AddField(
            model_name='commission',
            name='commission_type',
            field=models.PositiveIntegerField(choices=[(0, 'Медицинское обследование'), (1, 'Инструктаж')], default=0, verbose_name='Вид комиссии'),
        ),
        migrations.AddField(
            model_name='commission',
            name='decree',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Приказ'),
        ),
        migrations.AddField(
            model_name='commission',
            name='decree_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приказа'),
        ),
        migrations.RemoveField(
            model_name='commission',
            name='employee',
        ),
        migrations.CreateModel(
            name='CommissionEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_status', models.PositiveIntegerField(choices=[(0, 'Участник'), (1, 'Секретарь'), (2, 'Председатель')], default=0, verbose_name='Статус участника')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('commission', models.ForeignKey(db_column='commission_id', on_delete=django.db.models.deletion.PROTECT, to='companies.Commission', verbose_name='Комиссия')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, to='companies.Employee', verbose_name='Сотрудник')),
            ],
            options={
                'db_table': 'commission_employee',
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='employee',
            field=models.ManyToManyField(through='companies.CommissionEmployee', to='companies.Employee', verbose_name='Сотрудник'),
        ),
    ]
