# Generated by Django 2.2.6 on 2020-04-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20200414_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'verbose_name': 'Комиссия', 'verbose_name_plural': 'Комиссии'},
        ),
        migrations.AddField(
            model_name='commission',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
    ]
