# Generated by Django 2.2.6 on 2020-05-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_auto_20200524_0343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harmfulfactor',
            options={'verbose_name': 'Вредный фактор', 'verbose_name_plural': 'Вредные факторы'},
        ),
        migrations.AlterModelOptions(
            name='harmfulsubstance',
            options={'verbose_name': 'Вредное вещество', 'verbose_name_plural': 'Вредные вещества'},
        ),
        migrations.AlterModelOptions(
            name='workingconditionclass',
            options={'verbose_name': 'Класс условий труда', 'verbose_name_plural': 'Классы условий труда'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Вид работ и профессий', 'verbose_name_plural': 'Виды работ и профессий'},
        ),
    ]
