# Generated by Django 2.2.6 on 2020-04-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_auto_20200414_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_type',
            field=models.PositiveIntegerField(choices=[(1, 'Медицинское обследование'), (2, 'Инструктаж')], default=1, verbose_name='Вид комиссии'),
        ),
        migrations.AlterField(
            model_name='commissionemployee',
            name='member_status',
            field=models.PositiveIntegerField(choices=[(1, 'Участник'), (2, 'Секретарь'), (3, 'Председатель')], default=1, verbose_name='Статус участника'),
        ),
    ]
