# Generated by Django 2.2.6 on 2020-05-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20200524_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmfulfactor',
            name='inspection_frequency',
            field=models.CharField(choices=[('10 1t/1y', '1 раз в год'), ('20 1t/2y', '1 раз в 2 года')], default='10 1t/1y', max_length=50, verbose_name='Периодичность осмотра'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='inspection_frequency',
            field=models.CharField(choices=[('10 1t/1y', '1 раз в год'), ('20 1t/2y', '1 раз в 2 года')], default='10 1t/1y', max_length=50, verbose_name='Периодичность осмотра'),
        ),
    ]
