# Generated by Django 2.2.6 on 2020-04-15 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20200414_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='companies.Company', verbose_name='Компания'),
            preserve_default=False,
        ),
    ]
