# Generated by Django 2.2.6 on 2020-05-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20200525_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='harmfulsubstance',
            name='category',
            field=models.CharField(choices=[('chemical', 'Химический'), ('biological', 'Биологический'), ('industrial aerosols', 'Промышленный аэрозоли'), ('physical', 'Физические'), ('ongoing work', 'Проводимые работы. Категории должностей.')], default='chemical', max_length=50, verbose_name='Категория'),
        ),
    ]
