# Generated by Django 2.2.6 on 2020-04-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_commission_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionemployee',
            name='member_status',
            field=models.PositiveIntegerField(choices=[(1, 'Председатель'), (2, 'Секретарь'), (3, 'Участник')], default=1, verbose_name='Статус участника'),
        ),
    ]
