# Generated by Django 2.2.6 on 2020-04-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_auto_20200415_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionemployee',
            name='member_status',
            field=models.PositiveIntegerField(choices=[(1, 'Председатель'), (2, 'Секретарь'), (3, 'Участник')], default=3, verbose_name='Статус участника'),
        ),
    ]
