# Generated by Django 2.2.6 on 2020-04-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_eventemployee_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='frequency',
            field=models.CharField(choices=[('1/t', 'Единоразово'), ('1/m', 'Раз в месяц'), ('1/q', 'Раз в квартал'), ('2/y', 'Два раза в год'), ('1/y', 'Раз в год'), ('1/2y', 'Раз в два года'), ('1/w', 'Раз в неделю')], default='1/t', max_length=20, verbose_name='Периодичность'),
        ),
    ]
