# Generated by Django 2.2.6 on 2020-04-17 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_auto_20200417_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.Commission', verbose_name='Комиссия'),
        ),
    ]
