# Generated by Django 2.2.6 on 2020-04-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_event_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttype',
            name='order_num',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='workplace',
            field=models.ManyToManyField(related_name='employees', to='companies.Workplace', verbose_name='Рабочее место'),
        ),
    ]
