# Generated by Django 2.2.6 on 2020-04-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_auto_20200417_1631'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
