# Generated by Django 2.2.6 on 2020-04-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20200422_1616'),
        ('companies', '0022_auto_20200419_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='document_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.DocumentTemplate', verbose_name='Шаблон'),
        ),
    ]
