# Generated by Django 2.2.6 on 2020-04-25 14:00

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_commission_document_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка'),
        ),
    ]
