# Generated by Django 2.2.6 on 2020-04-25 14:26

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_auto_20200425_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='badge',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='badges/', verbose_name='Логотип'),
        ),
    ]
