# Generated by Django 2.2.6 on 2020-04-25 14:38

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_auto_20200425_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка'),
        ),
    ]
