# Generated by Django 2.2.6 on 2020-04-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_auto_20200425_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttype',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='companies.Company', verbose_name='Компания'),
            preserve_default=False,
        ),
    ]
