# Generated by Django 2.2.6 on 2020-04-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('path', models.CharField(default='', max_length=2000, verbose_name='Расположение')),
                ('params', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Параметры')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'db_table': 'document_template',
            },
        ),
    ]
