# Generated by Django 2.2.6 on 2020-05-14 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='file_template',
            field=models.FileField(blank=True, null=True, upload_to='doc_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='Файл шаблона'),
        ),
    ]
