# Generated by Django 2.2.6 on 2020-04-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200420_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='doc_generated/', verbose_name='Документ'),
        ),
    ]
