# Generated by Django 2.2.6 on 2020-04-21 12:48

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.get_file_path, verbose_name='Документ'),
        ),
    ]
