# Generated by Django 2.2.6 on 2020-04-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200421_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_file',
        ),
    ]
