# Generated by Django 2.2.6 on 2020-04-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='path',
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='file_template',
            field=models.FileField(blank=True, null=True, upload_to='files/doc_templates/', verbose_name='Файл шаблона'),
        ),
    ]
