# Generated by Django 2.2.6 on 2020-05-05 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplateParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255, verbose_name='Код')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('value_type', models.CharField(choices=[('number', 'Число'), ('text', 'Строка'), ('date', 'Дата'), ('boolean', 'Булево')], default='number', max_length=10, verbose_name='Формат значения')),
                ('value', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Значение')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('document_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.DocumentTemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Параметр шаблона документа',
                'verbose_name_plural': 'Параметры шаблона документа',
                'db_table': 'document_template_param',
            },
        ),
    ]
