# Generated by Django 2.2.6 on 2020-05-06 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_documenttemplateparam'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='template',
            field=models.BooleanField(default=False, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='documenttemplateparam',
            name='document_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_template_params', to='documents.DocumentTemplate', verbose_name='Шаблон'),
        ),
    ]
