# Generated by Django 2.2.6 on 2020-05-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='value_type',
            field=models.CharField(choices=[('text', 'Строка'), ('number', 'Число'), ('date', 'Дата'), ('boolean', 'Булево')], default='text', max_length=10, verbose_name='Формат значения'),
        ),
    ]
