from django.conf.urls import url

from .api.v1 import views as api_v1_views
from . import apps

app_name = apps.CompanyConfig.name

urlpatterns = [
    url(
        r'^api/v1/me/$',
        api_v1_views.MeAPIView.as_view(),
        name='me',
    ),
    url(
        r'^api/v1/companies/$',
        api_v1_views.CompanyListCreateAPIView.as_view(),
        name='list',
    ),
    url(
        r'^api/v1/companies/(?P<pk>\d+)/$',
        api_v1_views.CompanyRetrieveUpdateAPIView.as_view(),
        name='detail',
    ),
    url(
        r'^api/v1/users/(?P<pk>\d+)/$',
        api_v1_views.UserRetrieveUpdateAPIView.as_view(),
        name='detail',
    ),
    url(
        r'^api/v1/workplaces/$',
        api_v1_views.WorkplaceListCreateAPIView.as_view(),
        name='list',
    ),
    url(
        r'^api/v1/workplaces/(?P<pk>\d+)/$',
        api_v1_views.WorkplaceRetrieveUpdateAPIView.as_view(),
        name='detail',
    ),
    url(
        r'^api/v1/departments/$',
        api_v1_views.DepartmentListCreateAPIView.as_view(),
        name='list',
    ),
    url(
        r'^api/v1/departments/(?P<pk>\d+)/$',
        api_v1_views.DepartmentRetrieveUpdateAPIView.as_view(),
        name='detail',
    ),
    url(
        r'^api/v1/positions/$',
        api_v1_views.PositionListCreateAPIView.as_view(),
        name='list',
    ),
    url(
        r'^api/v1/positions/(?P<pk>\d+)/$',
        api_v1_views.PositionRetrieveUpdateAPIView.as_view(),
        name='detail',
    ),
    url(
        r'^api/v1/equipments/$',
        api_v1_views.EquipmentListCreateAPIView.as_view(),
        name='list',
    ),
    url(
        r'^api/v1/equipments/(?P<pk>\d+)/$',
        api_v1_views.EquipmentRetrieveUpdateAPIView.as_view(),
        name='detail',
    ),
    url(
        r'^api/v1/employees/$',
        api_v1_views.EmployeeListCreateAPIView.as_view(),
        name='list',
    ),
    url(
        r'^api/v1/employees/(?P<pk>\d+)/$',
        api_v1_views.EmployeeRetrieveUpdateAPIView.as_view(),
        name='detail',
    ),
    url(
        r'^api/v1/department-types/$',
        api_v1_views.DepartmentTypeListCreateAPIView.as_view(),
        name='list',
    ),
    url(
        r'^api/v1/department-types/(?P<pk>\d+)/$',
        api_v1_views.DepartmentTypeRetrieveUpdateAPIView.as_view(),
        name='detail',
    ),
    url(
        r'^api/v1/commissions-employees/$',
        api_v1_views.CommissionEmployeeListCreateAPIView.as_view(),
        name='list',
    ),
    url(
        r'^api/v1/commissions-employees/(?P<pk>\d+)/$',
        api_v1_views.CommissionEmployeeRetrieveUpdateAPIView.as_view(),
        name='detail',
    ),
    url(
        r'^api/v1/commissions/$',
        api_v1_views.CommissionListCreateAPIView.as_view(),
        name='list',
    ),
    url(
        r'^api/v1/commissions/(?P<pk>\d+)/$',
        api_v1_views.CommissionRetrieveUpdateAPIView.as_view(),
        name='detail',
    ),
    url(
        r'^api/v1/events/$',
        api_v1_views.EventListCreateAPIView.as_view(),
        name='list',
    ),
    url(
        r'^api/v1/events/(?P<pk>\d+)/$',
        api_v1_views.EventRetrieveUpdateAPIView.as_view(),
        name='detail',
    ),
    url(
        r'^api/v1/events-employees/$',
        api_v1_views.EventEmployeeListCreateAPIView.as_view(),
        name='list',
    ),
    url(
        r'^api/v1/events-document-templates/$',
        api_v1_views.EventDocumentTemplateListCreateAPIView.as_view(),
        name='list',
    ),
    url(
        r'^api/v1/events-document-templates/(?P<pk>\d+)/$',
        api_v1_views.EventDocumentTemplateRetrieveUpdateAPIView.as_view(),
        name='detail',
    ),
    url(
        r'^api/v1/event-types/$',
        api_v1_views.EventTypeListCreateAPIView.as_view(),
        name='bulk_list_create_update',
    ),
    url(
        r'^api/v1/assessment_cards/$',
        api_v1_views.AssessmentCardListCreateUpdateAPIView.as_view(),
        name='bulk_list_create_update',
    ),
    url(
        r'^api/v1/dicts/$',
        api_v1_views.DictListAPIView.as_view(),
        name='list',
    ),
]
