# Generated by Django 2.2.6 on 2020-05-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_auto_20200514_1134'),
        ('common', '0002_auto_20200511_0505'),
        ('companies', '0015_harmfulsubstance_category'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Entity')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.Company', verbose_name='Компания')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='Контент')),
                ('document_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.DocumentTemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'db_table': 'report',
            },
            bases=('common.entity',),
        ),
    ]
